/** Static, realistic seed dataset for CareerGraph. Small enough for a CognoDB free C0 instance. */

export type SeedSkill = { id: string; name: string; category: string; difficulty: string };

export const skills: SeedSkill[] = [
  { id: "s-html", name: "HTML", category: "Frontend", difficulty: "Beginner" },
  { id: "s-css", name: "CSS", category: "Frontend", difficulty: "Beginner" },
  { id: "s-js", name: "JavaScript", category: "Language", difficulty: "Beginner" },
  { id: "s-ts", name: "TypeScript", category: "Language", difficulty: "Intermediate" },
  { id: "s-react", name: "React", category: "Frontend", difficulty: "Intermediate" },
  { id: "s-next", name: "Next.js", category: "Frontend", difficulty: "Intermediate" },
  { id: "s-tailwind", name: "Tailwind CSS", category: "Frontend", difficulty: "Beginner" },
  { id: "s-redux", name: "Redux", category: "Frontend", difficulty: "Intermediate" },
  { id: "s-accessibility", name: "Web Accessibility", category: "Frontend", difficulty: "Intermediate" },
  { id: "s-node", name: "Node.js", category: "Backend", difficulty: "Intermediate" },
  { id: "s-express", name: "Express", category: "Backend", difficulty: "Intermediate" },
  { id: "s-nestjs", name: "NestJS", category: "Backend", difficulty: "Advanced" },
  { id: "s-python", name: "Python", category: "Language", difficulty: "Beginner" },
  { id: "s-fastapi", name: "FastAPI", category: "Backend", difficulty: "Intermediate" },
  { id: "s-django", name: "Django", category: "Backend", difficulty: "Intermediate" },
  { id: "s-go", name: "Go", category: "Language", difficulty: "Intermediate" },
  { id: "s-java", name: "Java", category: "Language", difficulty: "Intermediate" },
  { id: "s-spring", name: "Spring Boot", category: "Backend", difficulty: "Advanced" },
  { id: "s-rest", name: "REST APIs", category: "Backend", difficulty: "Beginner" },
  { id: "s-graphql", name: "GraphQL", category: "Backend", difficulty: "Intermediate" },
  { id: "s-grpc", name: "gRPC", category: "Backend", difficulty: "Advanced" },
  { id: "s-postgres", name: "PostgreSQL", category: "Database", difficulty: "Intermediate" },
  { id: "s-mysql", name: "MySQL", category: "Database", difficulty: "Beginner" },
  { id: "s-mongo", name: "MongoDB", category: "Database", difficulty: "Beginner" },
  { id: "s-redis", name: "Redis", category: "Database", difficulty: "Intermediate" },
  { id: "s-neo4j", name: "Graph Databases", category: "Database", difficulty: "Advanced" },
  { id: "s-sql", name: "SQL", category: "Database", difficulty: "Beginner" },
  { id: "s-datamodeling", name: "Data Modeling", category: "Database", difficulty: "Intermediate" },
  { id: "s-rabbitmq", name: "RabbitMQ", category: "Platform", difficulty: "Advanced" },
  { id: "s-kafka", name: "Kafka", category: "Platform", difficulty: "Advanced" },
  { id: "s-docker", name: "Docker", category: "DevOps", difficulty: "Intermediate" },
  { id: "s-k8s", name: "Kubernetes", category: "DevOps", difficulty: "Advanced" },
  { id: "s-aws", name: "AWS", category: "Cloud", difficulty: "Intermediate" },
  { id: "s-gcp", name: "GCP", category: "Cloud", difficulty: "Intermediate" },
  { id: "s-terraform", name: "Terraform", category: "DevOps", difficulty: "Advanced" },
  { id: "s-cicd", name: "CI/CD", category: "DevOps", difficulty: "Intermediate" },
  { id: "s-linux", name: "Linux", category: "Platform", difficulty: "Intermediate" },
  { id: "s-nginx", name: "Nginx", category: "Platform", difficulty: "Intermediate" },
  { id: "s-git", name: "Git", category: "Tooling", difficulty: "Beginner" },
  { id: "s-testing", name: "Testing", category: "Quality", difficulty: "Intermediate" },
  { id: "s-playwright", name: "Playwright", category: "Quality", difficulty: "Intermediate" },
  { id: "s-observability", name: "Observability", category: "DevOps", difficulty: "Advanced" },
  { id: "s-security", name: "Application Security", category: "Security", difficulty: "Advanced" },
  { id: "s-systemdesign", name: "System Design", category: "Architecture", difficulty: "Advanced" },
  { id: "s-microservices", name: "Microservices", category: "Architecture", difficulty: "Advanced" },
  { id: "s-pandas", name: "Pandas", category: "Data", difficulty: "Intermediate" },
  { id: "s-ml", name: "Machine Learning", category: "Data", difficulty: "Advanced" },
  { id: "s-airflow", name: "Airflow", category: "Data", difficulty: "Advanced" },
  { id: "s-spark", name: "Spark", category: "Data", difficulty: "Advanced" },
  { id: "s-figma", name: "Figma", category: "Design", difficulty: "Beginner" },
];

/** name -> name relationships between skills. */
export const relatedTo: [string, string, number][] = [
  ["HTML", "CSS", 9],
  ["CSS", "Tailwind CSS", 8],
  ["JavaScript", "TypeScript", 9],
  ["React", "Next.js", 9],
  ["React", "Redux", 8],
  ["React", "Tailwind CSS", 7],
  ["React", "Web Accessibility", 6],
  ["Node.js", "Express", 9],
  ["Node.js", "NestJS", 7],
  ["Express", "REST APIs", 8],
  ["REST APIs", "GraphQL", 7],
  ["GraphQL", "gRPC", 5],
  ["Python", "FastAPI", 8],
  ["Python", "Django", 8],
  ["Python", "Pandas", 8],
  ["Pandas", "Machine Learning", 7],
  ["Pandas", "Spark", 6],
  ["Airflow", "Spark", 6],
  ["Java", "Spring Boot", 9],
  ["Go", "gRPC", 7],
  ["SQL", "PostgreSQL", 9],
  ["SQL", "MySQL", 9],
  ["PostgreSQL", "Data Modeling", 8],
  ["MongoDB", "Data Modeling", 6],
  ["Graph Databases", "Data Modeling", 8],
  ["Redis", "PostgreSQL", 5],
  ["RabbitMQ", "Kafka", 7],
  ["Kafka", "Microservices", 7],
  ["Docker", "Kubernetes", 9],
  ["Kubernetes", "Terraform", 7],
  ["AWS", "Terraform", 8],
  ["AWS", "GCP", 6],
  ["Docker", "CI/CD", 7],
  ["CI/CD", "Testing", 7],
  ["Testing", "Playwright", 8],
  ["Linux", "Nginx", 8],
  ["Linux", "Docker", 7],
  ["Observability", "Kubernetes", 7],
  ["System Design", "Microservices", 9],
  ["Application Security", "REST APIs", 6],
  ["Figma", "Web Accessibility", 5],
  ["Git", "CI/CD", 6],
  ["Next.js", "Node.js", 7],
  ["Next.js", "Testing", 6],
  ["Next.js", "AWS", 5],
  ["Redux", "Testing", 6],
  ["Tailwind CSS", "Figma", 6],
  ["Web Accessibility", "Testing", 6],
  ["TypeScript", "NestJS", 7],
  ["Redux", "System Design", 4],
  ["Testing", "Observability", 5],
  ["Express", "Nginx", 5],
  ["MongoDB", "Redis", 5],
  ["Django", "PostgreSQL", 7],
  ["FastAPI", "Docker", 6],
  ["Spring Boot", "Microservices", 7],
  ["Machine Learning", "Airflow", 5],
];

export const prerequisiteOf: [string, string, number][] = [
  ["HTML", "React", 9],
  ["CSS", "Tailwind CSS", 8],
  ["JavaScript", "React", 10],
  ["JavaScript", "Node.js", 10],
  ["JavaScript", "TypeScript", 9],
  ["TypeScript", "NestJS", 8],
  ["React", "Next.js", 9],
  ["React", "Redux", 7],
  ["Node.js", "Express", 9],
  ["Express", "REST APIs", 7],
  ["REST APIs", "GraphQL", 7],
  ["SQL", "PostgreSQL", 9],
  ["SQL", "MySQL", 8],
  ["PostgreSQL", "Data Modeling", 7],
  ["Data Modeling", "Graph Databases", 8],
  ["Python", "FastAPI", 9],
  ["Python", "Django", 8],
  ["Python", "Pandas", 9],
  ["Pandas", "Machine Learning", 8],
  ["Java", "Spring Boot", 9],
  ["Linux", "Docker", 8],
  ["Docker", "Kubernetes", 9],
  ["Kubernetes", "Observability", 7],
  ["AWS", "Terraform", 7],
  ["Git", "CI/CD", 8],
  ["Testing", "Playwright", 8],
  ["Microservices", "System Design", 8],
  ["RabbitMQ", "Kafka", 6],
  ["Linux", "Nginx", 7],
  ["REST APIs", "Application Security", 6],
  ["Next.js", "System Design", 5],
  ["Tailwind CSS", "Web Accessibility", 5],
  ["Redux", "Testing", 5],
  ["FastAPI", "Docker", 6],
  ["Express", "Application Security", 5],
  ["Docker", "AWS", 7],
  ["AWS", "Observability", 6],
  ["GraphQL", "System Design", 5],
];

export const companies = [
  { id: "c-1", name: "Northwind Labs", industry: "SaaS", location: "Bengaluru, IN" },
  { id: "c-2", name: "Meridian Health", industry: "HealthTech", location: "Pune, IN" },
  { id: "c-3", name: "Kestrel Analytics", industry: "Data & AI", location: "Hyderabad, IN" },
  { id: "c-4", name: "Lumen Payments", industry: "FinTech", location: "Mumbai, IN" },
  { id: "c-5", name: "Orbital Commerce", industry: "E-commerce", location: "Remote" },
  { id: "c-6", name: "Baywood Logistics", industry: "Logistics", location: "Chennai, IN" },
  { id: "c-7", name: "Cobalt Security", industry: "Cybersecurity", location: "Bengaluru, IN" },
  { id: "c-8", name: "Fernway Learning", industry: "EdTech", location: "Delhi NCR, IN" },
  { id: "c-9", name: "Halcyon Cloud", industry: "Cloud Infrastructure", location: "Remote" },
  { id: "c-10", name: "Arbor Energy", industry: "CleanTech", location: "Ahmedabad, IN" },
  { id: "c-11", name: "Piper Media", industry: "Media", location: "Mumbai, IN" },
  { id: "c-12", name: "Sable Retail Group", industry: "Retail", location: "Kolkata, IN" },
  { id: "c-13", name: "Vantage Mobility", industry: "Mobility", location: "Bengaluru, IN" },
  { id: "c-14", name: "Ridgeline Insurance", industry: "InsurTech", location: "Gurugram, IN" },
  { id: "c-15", name: "Solstice Studios", industry: "Gaming", location: "Remote" },
];

type SeedJob = {
  id: string;
  title: string;
  level: string;
  location: string;
  remote: boolean;
  company: string;
  skills: string[];
};

export const jobs: SeedJob[] = [
  { id: "j-1", title: "Frontend Developer", level: "Junior", location: "Bengaluru, IN", remote: false, company: "c-1", skills: ["HTML", "CSS", "JavaScript", "React", "Git"] },
  { id: "j-2", title: "Senior Frontend Engineer", level: "Senior", location: "Remote", remote: true, company: "c-5", skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Testing", "Web Accessibility"] },
  { id: "j-3", title: "Full Stack Developer", level: "Mid", location: "Pune, IN", remote: false, company: "c-2", skills: ["React", "TypeScript", "Node.js", "Express", "PostgreSQL", "Docker", "REST APIs"] },
  { id: "j-4", title: "Senior Full Stack Engineer", level: "Senior", location: "Remote", remote: true, company: "c-9", skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "AWS", "GraphQL", "System Design"] },
  { id: "j-5", title: "Backend Engineer", level: "Mid", location: "Mumbai, IN", remote: false, company: "c-4", skills: ["Node.js", "Express", "PostgreSQL", "Redis", "REST APIs", "Docker"] },
  { id: "j-6", title: "Backend Engineer (Python)", level: "Mid", location: "Hyderabad, IN", remote: false, company: "c-3", skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "REST APIs"] },
  { id: "j-7", title: "Platform Engineer", level: "Senior", location: "Remote", remote: true, company: "c-9", skills: ["Kubernetes", "Docker", "Terraform", "AWS", "Linux", "Observability"] },
  { id: "j-8", title: "DevOps Engineer", level: "Mid", location: "Bengaluru, IN", remote: false, company: "c-13", skills: ["Docker", "CI/CD", "Linux", "AWS", "Nginx", "Git"] },
  { id: "j-9", title: "Data Engineer", level: "Mid", location: "Hyderabad, IN", remote: false, company: "c-3", skills: ["Python", "SQL", "Airflow", "Spark", "PostgreSQL"] },
  { id: "j-10", title: "Machine Learning Engineer", level: "Senior", location: "Hyderabad, IN", remote: false, company: "c-3", skills: ["Python", "Pandas", "Machine Learning", "Docker", "AWS"] },
  { id: "j-11", title: "Graph Data Engineer", level: "Senior", location: "Remote", remote: true, company: "c-3", skills: ["Graph Databases", "Data Modeling", "Python", "SQL", "Observability"] },
  { id: "j-12", title: "Java Backend Developer", level: "Mid", location: "Gurugram, IN", remote: false, company: "c-14", skills: ["Java", "Spring Boot", "MySQL", "REST APIs", "Docker"] },
  { id: "j-13", title: "Go Services Engineer", level: "Senior", location: "Bengaluru, IN", remote: false, company: "c-13", skills: ["Go", "gRPC", "Kubernetes", "PostgreSQL", "Microservices"] },
  { id: "j-14", title: "React Native Developer", level: "Mid", location: "Chennai, IN", remote: false, company: "c-6", skills: ["JavaScript", "React", "TypeScript", "Redux", "Git"] },
  { id: "j-15", title: "QA Automation Engineer", level: "Mid", location: "Pune, IN", remote: false, company: "c-2", skills: ["Testing", "Playwright", "JavaScript", "CI/CD"] },
  { id: "j-16", title: "Site Reliability Engineer", level: "Senior", location: "Remote", remote: true, company: "c-9", skills: ["Linux", "Kubernetes", "Observability", "Terraform", "Nginx"] },
  { id: "j-17", title: "Security Engineer", level: "Senior", location: "Bengaluru, IN", remote: false, company: "c-7", skills: ["Application Security", "Linux", "REST APIs", "Python", "Docker"] },
  { id: "j-18", title: "Junior Backend Developer", level: "Junior", location: "Kolkata, IN", remote: false, company: "c-12", skills: ["JavaScript", "Node.js", "SQL", "Git", "REST APIs"] },
  { id: "j-19", title: "Solutions Architect", level: "Lead", location: "Mumbai, IN", remote: false, company: "c-4", skills: ["System Design", "Microservices", "AWS", "Kafka", "PostgreSQL", "Observability"] },
  { id: "j-20", title: "Frontend Engineer (Design Systems)", level: "Mid", location: "Remote", remote: true, company: "c-11", skills: ["React", "Tailwind CSS", "TypeScript", "Figma", "Web Accessibility"] },
  { id: "j-21", title: "API Engineer", level: "Mid", location: "Delhi NCR, IN", remote: false, company: "c-8", skills: ["Node.js", "GraphQL", "REST APIs", "PostgreSQL", "Testing"] },
  { id: "j-22", title: "Cloud Engineer", level: "Mid", location: "Ahmedabad, IN", remote: false, company: "c-10", skills: ["AWS", "Terraform", "Docker", "Linux", "CI/CD"] },
  { id: "j-23", title: "Analytics Engineer", level: "Mid", location: "Remote", remote: true, company: "c-12", skills: ["SQL", "Python", "Pandas", "Data Modeling"] },
  { id: "j-24", title: "Streaming Data Engineer", level: "Senior", location: "Chennai, IN", remote: false, company: "c-6", skills: ["Kafka", "RabbitMQ", "Python", "Spark", "Docker"] },
  { id: "j-25", title: "Game Backend Developer", level: "Mid", location: "Remote", remote: true, company: "c-15", skills: ["Go", "Redis", "PostgreSQL", "Docker", "Microservices"] },
  { id: "j-26", title: "Technical Lead (Full Stack)", level: "Lead", location: "Bengaluru, IN", remote: false, company: "c-1", skills: ["React", "Node.js", "TypeScript", "System Design", "PostgreSQL", "AWS", "Testing"] },
  { id: "j-27", title: "Django Developer", level: "Mid", location: "Delhi NCR, IN", remote: false, company: "c-8", skills: ["Python", "Django", "PostgreSQL", "REST APIs", "Git"] },
  { id: "j-28", title: "NestJS Backend Engineer", level: "Senior", location: "Remote", remote: true, company: "c-5", skills: ["TypeScript", "NestJS", "Node.js", "PostgreSQL", "GraphQL", "Testing"] },
  { id: "j-29", title: "Observability Engineer", level: "Senior", location: "Bengaluru, IN", remote: false, company: "c-7", skills: ["Observability", "Kubernetes", "Linux", "Go", "CI/CD"] },
  { id: "j-30", title: "Web Developer", level: "Junior", location: "Mumbai, IN", remote: false, company: "c-11", skills: ["HTML", "CSS", "JavaScript", "Tailwind CSS", "Git"] },
];

export const resources = [
  { id: "r-1", title: "MDN Web Docs: HTML Basics", type: "Docs", url: "https://developer.mozilla.org/en-US/docs/Learn/HTML", skill: "HTML" },
  { id: "r-2", title: "CSS Layout Deep Dive", type: "Course", url: "https://web.dev/learn/css", skill: "CSS" },
  { id: "r-3", title: "JavaScript.info Modern Tutorial", type: "Tutorial", url: "https://javascript.info", skill: "JavaScript" },
  { id: "r-4", title: "TypeScript Handbook", type: "Docs", url: "https://www.typescriptlang.org/docs/handbook/intro.html", skill: "TypeScript" },
  { id: "r-5", title: "React Official Learn Guide", type: "Docs", url: "https://react.dev/learn", skill: "React" },
  { id: "r-6", title: "Next.js App Router Course", type: "Course", url: "https://nextjs.org/learn", skill: "Next.js" },
  { id: "r-7", title: "Tailwind CSS Fundamentals", type: "Docs", url: "https://tailwindcss.com/docs", skill: "Tailwind CSS" },
  { id: "r-8", title: "Redux Essentials", type: "Tutorial", url: "https://redux.js.org/tutorials/essentials/part-1-overview-concepts", skill: "Redux" },
  { id: "r-9", title: "Node.js Fundamentals", type: "Course", url: "https://nodejs.org/en/learn", skill: "Node.js" },
  { id: "r-10", title: "Express in Practice", type: "Docs", url: "https://expressjs.com/en/guide/routing.html", skill: "Express" },
  { id: "r-11", title: "NestJS Overview", type: "Docs", url: "https://docs.nestjs.com", skill: "NestJS" },
  { id: "r-12", title: "Python for Everybody", type: "Course", url: "https://www.py4e.com", skill: "Python" },
  { id: "r-13", title: "FastAPI Tutorial", type: "Docs", url: "https://fastapi.tiangolo.com/tutorial/", skill: "FastAPI" },
  { id: "r-14", title: "Django Getting Started", type: "Docs", url: "https://docs.djangoproject.com/en/stable/intro/", skill: "Django" },
  { id: "r-15", title: "A Tour of Go", type: "Tutorial", url: "https://go.dev/tour/", skill: "Go" },
  { id: "r-16", title: "Spring Boot Guides", type: "Docs", url: "https://spring.io/guides", skill: "Spring Boot" },
  { id: "r-17", title: "REST API Design Best Practices", type: "Article", url: "https://learn.microsoft.com/azure/architecture/best-practices/api-design", skill: "REST APIs" },
  { id: "r-18", title: "How to GraphQL", type: "Tutorial", url: "https://www.howtographql.com", skill: "GraphQL" },
  { id: "r-19", title: "PostgreSQL Tutorial", type: "Tutorial", url: "https://www.postgresqltutorial.com", skill: "PostgreSQL" },
  { id: "r-20", title: "SQL Bolt Interactive Lessons", type: "Tutorial", url: "https://sqlbolt.com", skill: "SQL" },
  { id: "r-21", title: "MongoDB University Basics", type: "Course", url: "https://learn.mongodb.com", skill: "MongoDB" },
  { id: "r-22", title: "Redis Data Structures", type: "Docs", url: "https://redis.io/docs/latest/develop/", skill: "Redis" },
  { id: "r-23", title: "Graph Data Modeling Guide", type: "Article", url: "https://neo4j.com/developer/data-modeling/", skill: "Graph Databases" },
  { id: "r-24", title: "Docker Getting Started", type: "Docs", url: "https://docs.docker.com/get-started/", skill: "Docker" },
  { id: "r-25", title: "Kubernetes Basics", type: "Tutorial", url: "https://kubernetes.io/docs/tutorials/kubernetes-basics/", skill: "Kubernetes" },
  { id: "r-26", title: "AWS Cloud Practitioner Essentials", type: "Course", url: "https://aws.amazon.com/training/", skill: "AWS" },
  { id: "r-27", title: "Terraform Up & Running Guides", type: "Docs", url: "https://developer.hashicorp.com/terraform/tutorials", skill: "Terraform" },
  { id: "r-28", title: "Testing JavaScript Applications", type: "Course", url: "https://testingjavascript.com", skill: "Testing" },
  { id: "r-29", title: "Playwright Docs", type: "Docs", url: "https://playwright.dev/docs/intro", skill: "Playwright" },
  { id: "r-30", title: "System Design Primer", type: "Article", url: "https://github.com/donnemartin/system-design-primer", skill: "System Design" },
];

export const people = [
  {
    id: "p-1",
    name: "Ramkumar R",
    title: "Aspiring Full Stack Developer",
    skills: [
      ["HTML", 5], ["CSS", 4], ["JavaScript", 4], ["React", 4], ["Git", 4],
      ["Tailwind CSS", 3], ["TypeScript", 3], ["REST APIs", 3],
    ] as [string, number][],
  },
  {
    id: "p-2",
    name: "Aisha Khan",
    title: "Backend Developer",
    skills: [
      ["JavaScript", 4], ["Node.js", 5], ["Express", 4], ["PostgreSQL", 4],
      ["SQL", 5], ["Docker", 3], ["REST APIs", 4], ["Git", 4], ["Redis", 3],
    ] as [string, number][],
  },
  {
    id: "p-3",
    name: "Daniel Osei",
    title: "Data Analyst moving to Data Engineering",
    skills: [
      ["Python", 5], ["SQL", 4], ["Pandas", 4], ["Data Modeling", 3],
      ["Git", 3], ["PostgreSQL", 3],
    ] as [string, number][],
  },
  {
    id: "p-4",
    name: "Meera Nair",
    title: "DevOps Practitioner",
    skills: [
      ["Linux", 5], ["Docker", 4], ["CI/CD", 4], ["AWS", 3], ["Nginx", 3],
      ["Git", 4], ["Kubernetes", 3],
    ] as [string, number][],
  },
  {
    id: "p-5",
    name: "Tomás Vidal",
    title: "Senior Frontend Engineer",
    skills: [
      ["JavaScript", 5], ["TypeScript", 5], ["React", 5], ["Next.js", 4],
      ["Tailwind CSS", 4], ["Testing", 4], ["Web Accessibility", 3],
      ["Redux", 4], ["Figma", 3], ["Git", 5],
    ] as [string, number][],
  },
];